image:
  file: .gitpod.Dockerfile
ports:
  - port: 9630
    onOpen: open-browser
vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - ms-python.python
    - ms-azuretools.vscode-docker
    - GitHub.copilot
