tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
vscode:
  extensions:
    - "cweijan.vscode-mysql-client2"
    - "ms-python.python"
    - "TabNine.tabnine-vscode"
    