image: gitpod/workspace-python-3.10
tasks:
  - before: printf 'export PATH="%s:$PATH"\n' "/workspace/bin" >> $HOME/.bashrc && exit
  - name: AWS install, configure, get secrets
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install -i /workspace/aws-cli -b /workspace/bin
      rm -r aws/
      rm awscliv2.zip
    command: |
      aws --profile default configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws --profile default configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
      aws s3 cp s3://skill-assessment-app/secrets/.env.download.sh .
      bash .env.download.sh
  - name: Pyenv install python
    init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade -r requirements.txt 
      echo "Prebuild is almost ready -- please be patient..."
    command: |
      source venv/bin/activate
vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - ms-python.python
    - ms-azuretools.vscode-docker
    - GitHub.copilot
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
