image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up --build
ports:
  - port: 9630
    onOpen: open-browser
vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - ms-python.python
    - ms-azuretools.vscode-docker
    - GitHub.copilot
