coverage:
  status:
    project:
      default:
        # basic
        target:
          number: 95%
        threshold: 0%
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
