name: Deploy CRUD app

on: workflow_dispatch

env:
  EB_PROD_ENVNAME: skill-app-crud-prod
  EB_CONFIG: ${{ secrets.EB_CONFIG }}
permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: crud

jobs:
  deploy:
    name: Deploy CRUD app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_TEST_DEPLOY }}
          role-session-name: GitHub-Action-Role
          aws-region: us-east-1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: create .prod.env file and EB config file
        run: |
          echo "$PROD_DOTENV" > .prod.env
          mkdir .elasticbeanstalk
          echo "$EB_CONFIG" > .elasticbeanstalk/config.yml
      - name: Get EB CLI version
        run: |
          pip install awsebcli --upgrade
          eb --version
      - name: Deploy to production
        run: |
          zip skill-app-crud.zip -r * .[^.]* -x "*cache*" -x "*venv*" -x "*instance*" -x "*vscode*" -x "*.git*" -x "*.ebextensions*" -x "*.elasticbeanstalk/logs*" -x "*htmlcov*"
          eb use $EB_PROD_ENVNAME && eb status $EB_PROD_ENVNAME && eb deploy --staged
