name: Test CRUD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    working-directory: crud
permissions:
  id-token: write
  contents: read
jobs:
  tests:
    name: Test CRUD
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_TEST_DEPLOY }}
          role-session-name: GitHub-Action-Role
          aws-region: us-east-1
      - name: Download .env
        run: |
          cd ../
          aws s3 cp s3://skill-assessment-app/secrets/.env.download.sh .
          bash .env.download.sh
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Pip install
        run: |
          pip install -r ../requirements.txt
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with coverage + pytest
        run: |
          docker-compose -f ../docker-compose.yml up -d --scale crud=0 
          python -m coverage run -m pytest
          if [ $? -ne 0 ]; then exit 1; fi  # Fail if pytest failed
          python -m coverage report
          python -m coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: crud
